services:
  file-converter-mcp:
    build: .
    container_name: file_converter
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - export-data:/output
    env_file:
      - .env

  file-export-server:
    build:
      dockerfile: file_server/dockerfile.server
    container_name: file_exporter
    restart: unless-stopped
    environment:
      - FILE_EXPORT_DIR=/output
    ports:
      - "9003:9003"
    volumes:
      - export-data:/output
    env_file:
      - .env

volumes:
  export-data:
